[package]
name = "chip8-emulator-rs"
description = "A simple to use chip8 emulator written in rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
sdl3 = { version = "0", features = [] }
sdl3-ttf-sys = { version = "0", features = [] }
